# Generated by Django 5.2.15 on 2026-07-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32, unique=True, verbose_name='Область')),
                ('last_value', models.PositiveBigIntegerField(default=0, verbose_name='Последнее значение')),
            ],
            options={
                'verbose_name': 'Последовательность номеров',
                'verbose_name_plural': 'Последовательности номеров',
            },
        ),
    ]
