# Generated by Django 5.2.15 on 2026-07-04 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_create_users_and_profiles'),
        ('vehicles', '0001_create_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to='vehicles.vehicle', verbose_name='Закреплённый автомобиль'),
        ),
    ]
