# Generated by Django 5.2.15 on 2026-07-04 18:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(help_text='Короткий код филиала, используется в трек-номерах (например BSH).', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Код филиала: 2–10 символов, только заглавные латинские буквы и цифры.', regex='^[A-Z0-9]{2,10}$')], verbose_name='Код')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона в международном формате, например +996700123456 (9–15 цифр).', regex='^\\+?\\d{9,15}$')], verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ('name',),
            },
        ),
    ]
