# Generated by Django 5.2.15 on 2026-07-04 22:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_add_authorship_and_city_links'),
        ('tariffs', '0001_create_tariffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('sender_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона в международном формате, например +996700123456 (9–15 цифр).', regex='^\\+?\\d{9,15}$')], verbose_name='Телефон отправителя')),
                ('sender_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес отправителя')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='Получатель')),
                ('receiver_phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона в международном формате, например +996700123456 (9–15 цифр).', regex='^\\+?\\d{9,15}$')], verbose_name='Телефон получателя')),
                ('receiver_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес получателя')),
                ('payment_type', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('qr', 'QR-оплата'), ('bank_transfer', 'Банковский перевод'), ('post_payment', 'Постоплата')], default='cash', max_length=20, verbose_name='Способ оплаты')),
                ('delivery_type', models.CharField(choices=[('branch_pickup', 'Выдача в филиале'), ('door_delivery', 'Доставка до двери')], default='branch_pickup', max_length=20, verbose_name='Тип доставки')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('insurance_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Страховка')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено')),
                ('price_details', models.JSONField(blank=True, default=dict, verbose_name='Разбивка стоимости')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('waiting_confirmation', 'Ожидает подтверждения'), ('need_correction', 'Требует исправления'), ('confirmed', 'Подтверждён'), ('waiting_payment', 'Ожидает оплаты'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('waiting_receive', 'Ожидает приёма груза'), ('received', 'Груз принят'), ('in_warehouse', 'На складе'), ('waiting_shipment', 'Ожидает рейса'), ('loaded', 'Погружен'), ('in_transit', 'В пути'), ('arrived', 'Прибыл'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Выдан получателю'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('returned', 'Возврат'), ('damaged', 'Повреждён'), ('lost', 'Утерян')], default='draft', max_length=25, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Версия')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='branches.branch', verbose_name='Филиал отправления')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tariffs.tariff', verbose_name='Тариф')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='branches.branch', verbose_name='Филиал назначения')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='orders.order', verbose_name='Заказ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tariffs.additionalservice', verbose_name='Услуга')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Услуга заказа',
                'verbose_name_plural': 'Услуги заказа',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=25, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=25, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['from_branch', 'status'], name='orders_orde_from_br_e2d10b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['to_branch', 'status'], name='orders_orde_to_bran_395657_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderserviceitem',
            constraint=models.UniqueConstraint(fields=('order', 'service'), name='unique_service_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'),
        ),
    ]
