# Generated by Django 5.2.15 on 2026-07-04 23:10

import apps.shipments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_add_authorship_and_city_links'),
        ('orders', '0001_create_orders'),
        ('packages', '0002_add_package_current_cell'),
        ('routes', '0001_create_routes'),
        ('vehicles', '0001_create_vehicles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('shipment_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер рейса')),
                ('planned_departure', models.DateTimeField(blank=True, null=True, verbose_name='План отправления')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое отправление')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое прибытие')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('planned', 'Запланирован'), ('ready', 'Готов к погрузке'), ('loading', 'Погрузка'), ('loaded', 'Погружен'), ('started', 'Стартовал'), ('in_transit', 'В пути'), ('gps_lost', 'Потеря GPS'), ('arrived', 'Прибыл'), ('unloading', 'Разгрузка'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('failed', 'Сорван')], default='draft', max_length=20, verbose_name='Статус')),
                ('version', models.PositiveIntegerField(default=1, editable=False, verbose_name='Версия')),
                ('arrival_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_in', to='branches.branch', verbose_name='Филиал прибытия')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('departure_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_out', to='branches.branch', verbose_name='Филиал отправления')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='routes.route', verbose_name='Маршрут')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('type', models.CharField(choices=[('accident', 'ДТП'), ('breakdown', 'Поломка'), ('delay', 'Задержка'), ('traffic', 'Пробка'), ('weather', 'Плохая погода'), ('damage', 'Повреждение груза'), ('loss', 'Потеря груза'), ('other', 'Другое')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.shipments.models.incident_photo_path, verbose_name='Фото')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='shipments.shipment', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('loaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Погружен')),
                ('unloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Разгружен')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='orders.order', verbose_name='Заказ')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='packages.package', verbose_name='Груз')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment', verbose_name='Рейс')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Груз рейса',
                'verbose_name_plural': 'Грузы рейса',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Из статуса')),
                ('to_status', models.CharField(max_length=20, verbose_name='В статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shipments.shipment', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'История статуса рейса',
                'verbose_name_plural': 'История статусов рейсов',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['driver', 'status'], name='shipments_s_driver__5ef385_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['vehicle', 'status'], name='shipments_s_vehicle_117bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['departure_branch', 'status'], name='shipments_s_departu_c42ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['shipment', 'type'], name='shipments_i_shipmen_6070d1_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'order'], name='shipments_s_shipmen_3ed47f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'package'), name='unique_package_per_shipment'),
        ),
    ]
