# Generated by Django 5.2.15 on 2026-09-28 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_create_routes'),
        ('shipments', '0001_create_shipments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('client_id', models.UUIDField(help_text='UUID, сгенерированный приложением: защита от дублей при ретраях.', unique=True, verbose_name='ID операции с устройства')),
                ('reached_at', models.DateTimeField(help_text='Время на устройстве в момент нажатия; может быть в прошлом (офлайн).', verbose_name='Время отметки')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий водителя')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('route_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='routes.routepoint', verbose_name='Точка маршрута')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='shipments.shipment', verbose_name='Рейс')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Отметка точки маршрута',
                'verbose_name_plural': 'Отметки точек маршрута',
                'ordering': ('reached_at',),
                'indexes': [models.Index(fields=['shipment', 'reached_at'], name='shipments_s_shipmen_ddff94_idx')],
                'constraints': [models.UniqueConstraint(fields=('shipment', 'route_point'), name='unique_checkpoint_per_route_point')],
            },
        ),
    ]
