# Generated by Django 5.2.15 on 2026-07-04 22:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_add_authorship_and_city_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Номер телефона в международном формате, например +996700123456 (9–15 цифр).', regex='^\\+?\\d{9,15}$')], verbose_name='Телефон')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь, м²')),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Макс. вес, кг')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='branches.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Заведующий')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('type', models.CharField(choices=[('receiving', 'Приёмка'), ('storage', 'Хранение'), ('dispatch', 'Отгрузка'), ('return', 'Возвраты'), ('damaged', 'Повреждённые'), ('archive', 'Архив')], default='storage', max_length=20, verbose_name='Тип')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Зона склада',
                'verbose_name_plural': 'Зоны склада',
                'ordering': ('warehouse', 'code'),
            },
        ),
        migrations.CreateModel(
            name='WarehouseCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('shelf', models.CharField(blank=True, max_length=20, verbose_name='Стеллаж')),
                ('row', models.CharField(blank=True, max_length=20, verbose_name='Ряд')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='Полка/уровень')),
                ('capacity_weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вместимость, кг')),
                ('capacity_volume', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вместимость, м³')),
                ('occupied_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Занято, кг')),
                ('occupied_volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Занято, м³')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='warehouses.warehousezone', verbose_name='Зона')),
            ],
            options={
                'verbose_name': 'Ячейка склада',
                'verbose_name_plural': 'Ячейки склада',
                'ordering': ('zone', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['branch'], name='warehouses__branch__72b634_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousezone',
            index=models.Index(fields=['warehouse', 'type'], name='warehouses__warehou_76f290_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousezone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_zone_code_per_warehouse'),
        ),
        migrations.AddIndex(
            model_name='warehousecell',
            index=models.Index(fields=['zone'], name='warehouses__zone_id_bdda50_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehousecell',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_cell_code_per_zone'),
        ),
        migrations.AddConstraint(
            model_name='warehousecell',
            constraint=models.CheckConstraint(condition=models.Q(('occupied_weight__lte', models.F('capacity_weight'))), name='cell_weight_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='warehousecell',
            constraint=models.CheckConstraint(condition=models.Q(('occupied_volume__lte', models.F('capacity_volume'))), name='cell_volume_within_capacity'),
        ),
    ]
