# Generated by Django 5.2.15 on 2026-07-04 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_create_orders'),
        ('packages', '0002_add_package_current_cell'),
        ('warehouses', '0001_create_warehouses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('description', models.TextField(verbose_name='Описание повреждения')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports', to='packages.package', verbose_name='Груз')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Акт повреждения',
                'verbose_name_plural': 'Акты повреждений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('received_by_name', models.CharField(max_length=255, verbose_name='Кто получил')),
                ('document_number', models.CharField(max_length=100, verbose_name='Документ')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='documents/signatures/', verbose_name='Подпись')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_confirmation', to='orders.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Подтверждение выдачи',
                'verbose_name_plural': 'Подтверждения выдачи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='Отчёт')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_sessions', to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('description', models.TextField(verbose_name='Обстоятельства')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_reports', to='packages.package', verbose_name='Груз')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Акт утери',
                'verbose_name_plural': 'Акты утери',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_scans', to='packages.package', verbose_name='Груз')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='warehouses.inventorysession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Скан инвентаризации',
                'verbose_name_plural': 'Сканы инвентаризации',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('session', 'package'), name='unique_scan_per_session')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('from_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='warehouses.warehousecell', verbose_name='Откуда')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='packages.package', verbose_name='Груз')),
                ('to_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='warehouses.warehousecell', verbose_name='Куда')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Перемещение груза',
                'verbose_name_plural': 'Перемещения грузов',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['package', 'created_at'], name='warehouses__package_068bcc_idx')],
            },
        ),
    ]
