"""Единый каталог кодов ошибок (ТЗ, раздел 24).

Каждая ошибка API обязана использовать код из этого каталога.
"""


class AuthErrors:
    INVALID_PHONE = 'AUTH_001'
    INVALID_PASSWORD = 'AUTH_002'
    TOKEN_EXPIRED = 'AUTH_003'
    INVALID_REFRESH_TOKEN = 'AUTH_004'
    USER_BLOCKED = 'AUTH_005'
    TOO_MANY_ATTEMPTS = 'AUTH_006'


class UserErrors:
    NOT_FOUND = 'USER_001'
    PHONE_TAKEN = 'USER_002'
    EMAIL_TAKEN = 'USER_003'
    PERMISSION_DENIED = 'USER_004'
    DELETED = 'USER_005'
    ROLE_FORBIDDEN = 'USER_006'


class OrderErrors:
    NOT_FOUND = 'ORDER_001'
    ALREADY_PAID = 'ORDER_002'
    CANCELLED = 'ORDER_003'
    INVALID_STATUS = 'ORDER_004'
    SHIPMENT_ASSIGNED = 'ORDER_005'
    COMPLETED = 'ORDER_006'
    LOCKED = 'ORDER_007'
    PAYMENT_REQUIRED = 'ORDER_008'
    PACKAGE_MISSING = 'ORDER_009'
    QR_MISSING = 'ORDER_010'


class ShipmentErrors:
    NOT_FOUND = 'SHIPMENT_001'
    VEHICLE_BUSY = 'SHIPMENT_002'
    DRIVER_BUSY = 'SHIPMENT_003'
    STARTED = 'SHIPMENT_004'
    COMPLETED = 'SHIPMENT_005'
    WEIGHT_LIMIT = 'SHIPMENT_006'
    VOLUME_LIMIT = 'SHIPMENT_007'
    MISSING_PACKAGE = 'SHIPMENT_008'
    INVALID_ROUTE = 'SHIPMENT_009'


class PackageErrors:
    NOT_FOUND = 'PACKAGE_001'
    QR_ALREADY_EXISTS = 'PACKAGE_002'
    LOST = 'PACKAGE_003'
    DAMAGED = 'PACKAGE_004'
    ALREADY_LOADED = 'PACKAGE_005'
    ALREADY_DELIVERED = 'PACKAGE_006'
    WRONG_CELL = 'PACKAGE_007'


class PaymentErrors:
    FAILED = 'PAYMENT_001'
    ALREADY_EXISTS = 'PAYMENT_002'
    CANCELLED = 'PAYMENT_003'
    REFUND_FAILED = 'PAYMENT_004'
    INVOICE_MISSING = 'PAYMENT_005'
    DEBT_EXISTS = 'PAYMENT_006'


class GPSErrors:
    OFFLINE = 'GPS_001'
    INVALID_COORDINATES = 'GPS_002'
    ROUTE_DEVIATION = 'GPS_003'
    VEHICLE_OFFLINE = 'GPS_004'
    SPEED_LIMIT = 'GPS_005'
    DEVICE_NOT_REGISTERED = 'GPS_006'


class WarehouseErrors:
    FULL = 'WAREHOUSE_001'
    CELL_FULL = 'WAREHOUSE_002'
    QR_MISSING = 'WAREHOUSE_003'
    PACKAGE_MISSING = 'WAREHOUSE_004'
    INVENTORY_LOCKED = 'WAREHOUSE_005'
    INVALID_MOVEMENT = 'WAREHOUSE_006'


class TariffErrors:
    NOT_FOUND = 'TARIFF_001'


class SystemErrors:
    INTERNAL = 'SYSTEM_001'
    DATABASE = 'SYSTEM_002'
    REDIS = 'SYSTEM_003'
    STORAGE = 'SYSTEM_004'
    TIMEOUT = 'SYSTEM_005'
    EXTERNAL_PROVIDER = 'SYSTEM_006'
    UNKNOWN = 'SYSTEM_007'


VALIDATION_ERROR = 'VALIDATION_ERROR'
PERMISSION_DENIED = 'PERMISSION_DENIED'
NOT_FOUND = 'NOT_FOUND'
CONFLICT = 'CONFLICT'
