# Generated by Django 5.2.15 on 2026-07-04 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_create_shipments'),
        ('vehicles', '0001_create_vehicles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('warehouse', 'Склад'), ('branch', 'Филиал'), ('checkpoint', 'Контрольная точка'), ('delivery', 'Зона доставки'), ('custom', 'Произвольная')], default='custom', max_length=20, verbose_name='Тип')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта центра')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота центра')),
                ('radius_m', models.PositiveIntegerField(default=500, verbose_name='Радиус, м')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Геозона',
                'verbose_name_plural': 'Геозоны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GPSEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stop', 'Остановка'), ('long_stop', 'Долгая остановка'), ('enter_geofence', 'Вход в геозону'), ('exit_geofence', 'Выход из геозоны'), ('route_deviation', 'Отклонение от маршрута'), ('overspeed', 'Превышение скорости'), ('offline', 'Потеря связи')], max_length=20, verbose_name='Тип')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_events', to='shipments.shipment', verbose_name='Рейс')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_events', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'GPS-событие',
                'verbose_name_plural': 'GPS-события',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['vehicle', 'type'], name='gps_gpseven_vehicle_78085e_idx'), models.Index(fields=['shipment', 'created_at'], name='gps_gpseven_shipmen_98f9df_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('altitude', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='Высота, м')),
                ('speed', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Скорость, км/ч')),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс, °')),
                ('accuracy', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Погрешность, м')),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Заряд, %')),
                ('device_id', models.CharField(blank=True, max_length=64, verbose_name='Device ID')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='Версия приложения')),
                ('device_time', models.DateTimeField(verbose_name='Время устройства')),
                ('server_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время сервера')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_logs', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='shipments.shipment', verbose_name='Рейс')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'GPS-точка',
                'verbose_name_plural': 'GPS-журнал',
                'ordering': ('-server_time',),
                'indexes': [models.Index(fields=['vehicle', 'server_time'], name='gps_gpslog_vehicle_7a190d_idx'), models.Index(fields=['shipment', 'server_time'], name='gps_gpslog_shipmen_d1fa29_idx'), models.Index(fields=['driver', 'server_time'], name='gps_gpslog_driver__5347a1_idx')],
            },
        ),
    ]
