# Generated by Django 5.2.15 on 2026-07-04 22:58

import apps.packages.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_create_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('qr_code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='QR-код')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Штрихкод')),
                ('qr_generated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='QR создан')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Вес, кг')),
                ('length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина, см')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина, см')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота, см')),
                ('volume', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объём, м³')),
                ('declared_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объявленная ценность')),
                ('fragile', models.BooleanField(default=False, verbose_name='Хрупкий')),
                ('dangerous', models.BooleanField(default=False, verbose_name='Опасный')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('received', 'Принят'), ('checked', 'Проверен'), ('stored', 'Размещён'), ('waiting_loading', 'Ожидает погрузки'), ('loaded', 'Погружен'), ('in_transit', 'В пути'), ('unloaded', 'Разгружен'), ('ready_for_pickup', 'Готов к выдаче'), ('delivered', 'Выдан'), ('returned', 'Возврат'), ('damaged', 'Повреждён'), ('lost', 'Утерян')], default='created', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='orders.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Грузовое место',
                'verbose_name_plural': 'Грузовые места',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PackagePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('image', models.ImageField(upload_to=apps.packages.models.package_photo_path, verbose_name='Фото')),
                ('type', models.CharField(choices=[('receiving', 'Приём'), ('loading', 'Погрузка'), ('unloading', 'Разгрузка'), ('delivery', 'Выдача'), ('damage', 'Повреждение')], max_length=20, verbose_name='Этап')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='packages.package', verbose_name='Груз')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото груза',
                'verbose_name_plural': 'Фото грузов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_pa_status_1e0453_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['order', 'status'], name='packages_pa_order_i_95c527_idx'),
        ),
        migrations.AddIndex(
            model_name='packagephoto',
            index=models.Index(fields=['package', 'type'], name='packages_pa_package_020e27_idx'),
        ),
    ]
