# Generated by Django 5.2.15 on 2026-07-04 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_create_packages'),
        ('warehouses', '0001_create_warehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='warehouses.warehousecell', verbose_name='Текущая ячейка'),
        ),
    ]
