# Generated by Django 5.2.15 on 2026-07-04 21:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='Роль')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_uuid', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('event_type', models.CharField(blank=True, max_length=100, verbose_name='Тип события')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='Старые данные')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='Новые данные')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='Request ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at',),
            },
        ),
    ]
