# Generated by Django 5.2.15 on 2026-07-04 23:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_add_authorship_and_city_links'),
        ('orders', '0001_create_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Баланс')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cashbox', to='branches.branch', verbose_name='Филиал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ('branch__name',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('payment_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('currency', models.CharField(default='KGS', max_length=3, verbose_name='Валюта')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank_transfer', 'Банковский перевод'), ('qr', 'QR-оплата'), ('pos', 'POS-терминал'), ('online', 'Онлайн')], max_length=20, verbose_name='Метод')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Внешний ID транзакции')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён'), ('refunded', 'Возвращён')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Заказ')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='НДС, %')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Выставлен')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('reason', models.CharField(choices=[('customer_request', 'Запрос клиента'), ('cancelled_order', 'Отмена заказа'), ('wrong_payment', 'Ошибочный платёж'), ('duplicate_payment', 'Дубль платежа'), ('other', 'Другое')], max_length=30, verbose_name='Причина')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.payment', verbose_name='Платёж')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('refund', 'Возврат'), ('transfer', 'Перемещение'), ('correction', 'Корректировка')], max_length=20, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashbox', verbose_name='Касса')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.payment', verbose_name='Платёж')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыта')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Остаток на открытие')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Остаток на закрытие')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='finance.cashbox', verbose_name='Касса')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Кассовая смена',
                'verbose_name_plural': 'Кассовые смены',
                'ordering': ('-opened_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('cashbox',), name='single_open_session_per_cashbox')],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма долга')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Погашено')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('partially_paid', 'Частично погашен'), ('closed', 'Закрыт'), ('overdue', 'Просрочен')], default='open', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='orders.order', verbose_name='Заказ')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженности',
                'ordering': ('due_date',),
                'indexes': [models.Index(fields=['status', 'due_date'], name='finance_deb_status_227040_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, editable=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Удалено')),
                ('period_type', models.CharField(max_length=10, verbose_name='Период')),
                ('period_date', models.DateField(verbose_name='Дата периода')),
                ('data', models.JSONField(default=dict, verbose_name='Показатели')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Финансовый отчёт',
                'verbose_name_plural': 'Финансовые отчёты',
                'ordering': ('-period_date',),
                'constraints': [models.UniqueConstraint(fields=('period_type', 'period_date'), name='unique_report_per_period')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='finance_pay_order_i_47cefe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='finance_pay_transac_c95172_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='finance_pay_created_859d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['cashbox', 'type'], name='finance_tra_cashbox_145247_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='finance_tra_created_ef4f06_idx'),
        ),
    ]
